### ISSUE TITLE
Easily copy Quote

### ISSUE THREAD

**Issue by omerfarukyilmaz** [mdilaveroglu/Quoter-Android#5]
"Long press on a quote, choose copy to copy to it to the phone's clipboard".

Requested by a Quoter user.

**Comment by mdilaveroglu** [comment]
Done.

**Comment by mdilaveroglu** [comment]
Mehmet

[starCopy.pdf](https://github.com/mdilaveroglu/Quoter-Android/files/3533233/starCopy.pdf)

**Comment by mdilaveroglu** [comment]
Test comment
